server_port: 5051
fight_server_port: 5052
server_ip: 172.23.0.1
fight_server_ip: 172.23.0.1
window_caption: Client game
screen_width: 800
screen_height: 800
town_width: 200
town_height: 200
player_width: 25
player_height: 25
fight_time_wait: 5
fight_time: 5
score_item_time: 2